# How a piece of Ceres-C is declared.
#
# All eight libraries (§2 of the architecture plan) are identical on the inside: a name, what it
# depends on, headers under include/, implementation under src/. Declaring them through a function
# instead of eight near-identical CMakeLists.txt keeps that one shape enforced instead of
# copy-pasted.
#
# About the globs: CONFIGURE_DEPENDS makes CMake look again on every build, so a new .cpp/.h shows
# up without reconfiguring by hand - important while working through the phased plan (§13), where
# a library that was placeholder-only yesterday gains its first real source file today.

include_guard(GLOBAL)

# The placeholder translation unit's text. A static library needs at least one .cpp for CMake to
# know which linker to treat it with, and most libraries here start empty - their turn comes in a
# later phase (§13). An empty static file would make the MSVC linker warn (LNK4221) and keeps
# CMake from deducing the target's language, so here's a symbol and nothing else. As soon as a
# real .cpp appears in src/, this file drops out of the build without anyone deleting it.
set(CERESC_PLACEHOLDER_SOURCE [[
// Generated by CMake. Not version-controlled and never needs touching.
//
// This library has no sources yet - see the phased plan (architecture plan, §13) for when it's
// implemented. An empty static file would make the MSVC linker warn (LNK4221) and keeps CMake
// from deducing the target's language, so here's a symbol and nothing else. It disappears from
// the build on its own the moment src/ gains a real .cpp.

namespace ceresc::detail
{
	int placeholderTranslationUnit_@name@() noexcept;
	int placeholderTranslationUnit_@name@() noexcept { return 0; }
}
]])

# ceresc_add_library(<name> [DEPENDS <name> ...])
#
# Creates ceresc_<name> (static) and the ceresc::<name> alias. include/ headers are public and
# src/ ones aren't - the boundary is a compile error the moment anyone tries to cross it.
function(ceresc_add_library name)
	cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "DEPENDS")

	set(root "${CMAKE_CURRENT_SOURCE_DIR}")
	set(target "ceresc_${name}")

	file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${root}/src/*.cpp")
	file(GLOB_RECURSE private_headers CONFIGURE_DEPENDS "${root}/src/*.h")
	file(GLOB_RECURSE public_headers CONFIGURE_DEPENDS "${root}/include/*.h")

	set(compiled ${sources})
	if(NOT compiled)
		set(placeholder "${CMAKE_CURRENT_BINARY_DIR}/${target}_placeholder.cpp")
		if(NOT EXISTS "${placeholder}")
			# string(CONFIGURE) to substitute @name@: the content of a bracket-argument is stored
			# literally, so a ${} inside it wouldn't expand when writing it out.
			string(CONFIGURE "${CERESC_PLACEHOLDER_SOURCE}" placeholder_text @ONLY)
			file(WRITE "${placeholder}" "${placeholder_text}")
		endif()
		set(compiled "${placeholder}")
	endif()

	# No loose files in this list. When Visual Studio adds a new file to a CMake project, it edits
	# the nearest add_library() it can find - and the one it finds is this one, shared by all
	# eight libraries, so one library's header ends up claimed by all of them with a relative path
	# that doesn't resolve from any of them. The globs above already pick up any new file: just
	# create it in its folder and that's it.
	add_library(${target} STATIC ${compiled} ${private_headers} ${public_headers})
	add_library(ceresc::${name} ALIAS ${target})

	# BUILD_INTERFACE and not a bare path: the day this gets installed or split out into its own
	# repository, the source tree's path won't mean anything to whoever consumes it.
	target_include_directories(${target}
		PUBLIC  "$<BUILD_INTERFACE:${root}/include>"
		PRIVATE "${root}/src")

	target_link_libraries(${target}
		PUBLIC  ceresc::settings
		PRIVATE ceresc::warnings)

	foreach(dependency IN LISTS ARG_DEPENDS)
		target_link_libraries(${target} PUBLIC ceresc::${dependency})
	endforeach()

	set_target_properties(${target} PROPERTIES FOLDER "libs")

	# So the Visual Studio Solution Explorer shows the real tree instead of a flat list.
	if(public_headers)
		source_group(TREE "${root}/include" PREFIX "include" FILES ${public_headers})
	endif()
	if(sources OR private_headers)
		source_group(TREE "${root}/src" PREFIX "src" FILES ${sources} ${private_headers})
	endif()

	list(LENGTH sources source_count)
	set_property(GLOBAL APPEND PROPERTY CERESC_LIBRARY_STATUS "${name}=${source_count}")
endfunction()

# ceresc_add_tests(<name>)
#
# A library's unit suite, if it already has files under tests/. Called from the library's own
# CMakeLists, next to its ceresc_add_library().
function(ceresc_add_tests name)
	if(NOT CERESC_BUILD_TESTS)
		return()
	endif()

	file(GLOB sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cpp")
	if(NOT sources)
		return()
	endif()

	if(NOT TARGET ceresc_test_main)
		message(STATUS "ceresc: ${name} already has tests, but tests/framework/main.cpp is missing - suite skipped")
		return()
	endif()

	set(target "ceresc_${name}_tests")
	add_executable(${target} ${sources})
	target_link_libraries(${target} PRIVATE ceresc::${name} ceresc::test_main ceresc::warnings)

	# A library's suite does see its private headers. It's the only exception to the include/ vs
	# src/ boundary, and it's deliberate: a unit test that can only touch the public API isn't
	# unitary.
	target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")

	set_target_properties(${target} PROPERTIES FOLDER "tests")

	add_test(NAME ${name} COMMAND ${target})
endfunction()

# ceresc_report_status()
#
# At configure time, a one-line tally of which libraries already have real sources and which are
# still placeholders - a cheap way to see where the phased plan (§13) currently stands without
# opening every folder.
function(ceresc_report_status)
	get_property(entries GLOBAL PROPERTY CERESC_LIBRARY_STATUS)

	set(implemented "")
	set(pending "")
	foreach(entry IN LISTS entries)
		string(REPLACE "=" ";" parts "${entry}")
		list(GET parts 0 name)
		list(GET parts 1 count)
		if(count EQUAL 0)
			list(APPEND pending "${name}")
		else()
			list(APPEND implemented "${name} (${count})")
		endif()
	endforeach()

	message(STATUS "")
	message(STATUS "Ceres-C ${PROJECT_VERSION} - C++${CMAKE_CXX_STANDARD}, ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
	if(implemented)
		list(JOIN implemented ", " text)
		message(STATUS "  implemented : ${text}")
	endif()
	if(pending)
		list(JOIN pending ", " text)
		message(STATUS "  placeholder : ${text}")
	endif()
	message(STATUS "")
endfunction()
